name: Cargo B(inary)Install

description: Install binaries with cargo-binstall

inputs:
  args:
    description: List of arguments to pass to `cargo binstall`
    required: true

runs:
  using: composite

  steps:
      - name: Install cargo-binstall
        uses: taiki-e/install-action@cargo-binstall

      - name: Running cargo-binstall with provided arguments
        run: cargo binstall ${{ inputs.args }}
