[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
authors = ["Yagiz Nizipli <yagiz@nizipli.com"]
description = "Pacquet"
edition = "2021"
homepage = "https://github.com/anonrig/pacquet"
keywords = ["Node.js"]
license = "MIT"
repository = "https://github.com/anonrig/pacquet"

[workspace.dependencies]
# Release:
# * Edit these versions, commit
# * cargo ws version --amend --no-git-tag --no-git-push
# publish = true
pacquet_cli = { version = "0.0.1", path = "crates/cli" }

# publish = false
pacquet_registry = { path = "crates/registry" }
pacquet_tarball = { path = "crates/tarball" }
pacquet_package_json = { path = "crates/package_json" }
pacquet_lockfile = { path = "crates/lockfile" }

anyhow = { version = "1.0.71" }
async-recursion = { version = "1.0.4" }
clap = { version = "4", features = ["derive"] }
elsa = { version = "1.8.1" }
flate2 = { version = "1.0.26" }
futures-util = { version = "0.3.28" }
reqwest = { version = "0.11", features = ["json", "stream"] }
reqwest-middleware = { version = "0.2.2" }
reqwest-retry = { version = "0.2.2" }
node-semver = { version = "2.1.0" }
serde = { version = "1.0.164", features = ["derive"] }
serde_yaml = { version = "0.9.1" }
serde_json = { version = "1.0.99" }
tar = { version = "0.4.38" }
thiserror = { version = "1.0.40" }
tracing = { version = "0.1.37" }
tracing-chrome = { version = "0.7.1" }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread"] }
uuid = { version = "1.4.0", features = ["v4", "fast-rng"] }

[workspace.metadata.workspaces]
allow_branch = "main"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"
debug = false
panic = "abort"   # Let it crash and force ourselves to write safe Rust.

# Use the `--profile release-debug` flag to show symbols in release mode.
# e.g. `cargo build --profile release-debug`
[profile.release-debug]
inherits = "release"
strip = false
debug = true
