[package]
name                  = "pacquet_cli"
version               = "0.0.1"
publish               = false
authors.workspace     = true
description.workspace = true
edition.workspace     = true
homepage.workspace    = true
keywords.workspace    = true
license.workspace     = true
repository.workspace  = true

[[bin]]
name = "pacquet"
path = "src/bin/main.rs"

[dependencies]
pacquet_cafs         = { workspace = true }
pacquet_executor     = { workspace = true }
pacquet_npmrc        = { workspace = true }
pacquet_package_json = { workspace = true }
pacquet_registry     = { workspace = true }
pacquet_tarball      = { workspace = true }

async-recursion    = { workspace = true }
async-trait        = { workspace = true }
clap               = { workspace = true }
futures            = { workspace = true }
futures-util       = { workspace = true }
miette             = { workspace = true }
rayon              = { workspace = true }
reflink-copy       = { workspace = true }
reqwest            = { workspace = true }
reqwest-middleware = { workspace = true }
reqwest-retry      = { workspace = true }
node-semver        = { workspace = true }
serde              = { workspace = true }
serde_json         = { workspace = true }
thiserror          = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
tokio              = { workspace = true }

[dev-dependencies]
insta    = { workspace = true }
tempfile = { workspace = true }
walkdir  = { workspace = true }
