[package]
name                  = "pacquet_cli"
version               = "0.0.1"
publish               = false
authors.workspace     = true
description.workspace = true
edition.workspace     = true
homepage.workspace    = true
keywords.workspace    = true
license.workspace     = true
repository.workspace  = true

[[bin]]
name = "pacquet"
path = "src/main.rs"

[dependencies]
pacquet_package_json    = { workspace = true }
pacquet_package_manager = { workspace = true }
pacquet_executor        = { workspace = true }
pacquet_npmrc           = { workspace = true }
pacquet_cafs            = { workspace = true }

clap               = { workspace = true }
miette             = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
tokio              = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
