[package]
name                  = "pacquet_lockfile"
version               = "0.0.1"
publish               = false
authors.workspace     = true
description.workspace = true
edition.workspace     = true
homepage.workspace    = true
keywords.workspace    = true
license.workspace     = true
repository.workspace  = true

[dependencies]
pacquet_diagnostics = { workspace = true }

derive_more = { workspace = true }
node-semver = { workspace = true }
pipe-trait  = { workspace = true }
serde       = { workspace = true }
serde_yaml  = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
text-block-macros = { workspace = true }
