[package]
name                  = "pacquet-package-manifest"
version               = "0.0.1"
publish               = false
authors.workspace     = true
description.workspace = true
edition.workspace     = true
homepage.workspace    = true
keywords.workspace    = true
license.workspace     = true
repository.workspace  = true

[dependencies]
derive_more = { workspace = true }
miette      = { workspace = true }
serde       = { workspace = true }
serde_json  = { workspace = true }
strum       = { workspace = true }

[dev-dependencies]
pipe-trait        = { workspace = true }
pretty_assertions = { workspace = true }
tempfile          = { workspace = true }
insta             = { workspace = true }
