[package]
name                  = "pacquet-cafs"
version               = "0.0.1"
publish               = false
authors.workspace     = true
description.workspace = true
edition.workspace     = true
homepage.workspace    = true
keywords.workspace    = true
license.workspace     = true
repository.workspace  = true

[dependencies]
pacquet-store-dir = { workspace = true }

derive_more = { workspace = true }
miette      = { workspace = true }
ssri        = { workspace = true }

[dev-dependencies]
tempfile          = { workspace = true }
pretty_assertions = { workspace = true }
