[package]
name                  = "pacquet-micro-benchmark"
version               = "0.0.0"
publish               = false
authors.workspace     = true
description.workspace = true
edition.workspace     = true
homepage.workspace    = true
keywords.workspace    = true
license.workspace     = true
repository.workspace  = true

[[bin]]
name = "micro-benchmark"
path = "src/main.rs"

[dependencies]
pacquet-registry  = { workspace = true }
pacquet-store-dir = { workspace = true }
pacquet-tarball   = { workspace = true }

clap         = { workspace = true }
criterion    = { workspace = true }
mockito      = { workspace = true }
tokio        = { workspace = true }
tempfile     = { workspace = true }
pipe-trait   = { workspace = true }
project-root = { workspace = true }
reqwest      = { workspace = true }
node-semver  = { workspace = true }
